Enable settings conversion to CAF
tenzir/vast pull request #1055
Opened 2020-09-10 15:51 UTC by mavam

2020-09-15 14:54 UTC, dominiklohmann requested changes
Mostly fine by me except for one small, subtle issue in the code.

Please change the test record for the unit test such that it contains a list that contains at least one different type, e.g., record.

I did not test this locally; the unit tests running through cover this functionality quite well.

2020-09-15 14:54 UTC, dominiklohmann commented on libvast/vast/concept/convertible/to.hpp
> +  using return_type = decltype(convert(from, std::declval<To&>(), opts...));
```suggestion
  using return_type = decltype(convert(from, std::declval<To&>(), std::forward<Opts>(opts)...));
```

+ reformatting

2020-09-15 20:45 UTC, dominiklohmann approved these changes
Approving as is, just one remark: Why did you move from `caf::settings` to `caf::dictionary<caf::config_value>`? The former is an alias of the latter, but I find `caf::settings` to be the more idiomatic type to enable conversion to.

2020-09-16 06:36 UTC, mavam commented
> Why did you move from `caf::settings` to `caf::dictionary<caf::config_value>`?

The reason is that `caf::settings` is just a top-level alias. The real recursive structure is a `config_value` and this is what I'd like the user of the API to remember: a `config_value` can contain a `dictionary` of `config_value`s. Since the recursion occurs in the implementation, I find it cleaning to stick to a single set of vocabulary.

2020-09-16 06:36 UTC, merged