Enable loading of concepts from disk
tenzir/vast pull request #1102
Opened 2020-10-20 06:47 UTC by tobim

TODO:
- [ ] Integration Test
- [ ] Changelog entry

2020-10-21 09:02 UTC, mavam requested changes
Nice work overall.

It would be great if we can test an ill-formed concept definition as well.

2020-10-21 09:02 UTC, mavam commented on libvast/src/schema.cpp
> +              std::inserter(result, result.end()));
```suggestion
    result.insert(result.end(), user_dirs->begin(), user_dirs->end());
```

2020-10-21 09:47 UTC, tobim commented on schema/ecs.yaml
> +      - zeek.x509.id.orig_h
Yes, I thought about using `zeek.conn_id` instead. This would depend on nested layouts though.

2020-10-21 14:50 UTC, mavam commented on schema/ecs.yaml
> +      - zeek.x509.id.orig_h
I haven't even though of this, but yeah, that's even another angle.

2020-10-22 14:17 UTC, mavam requested changes

2020-10-22 14:17 UTC, mavam commented on CHANGELOG.md
> +  schemes of each individual data source.
```suggestion
- 🧬 The query language now comes with support for *concepts*, the first part of
  taxonomies. Concepts is a mechanism to unify the various naming
  schemes of different data formats into a single, coherent nomenclature.
```

2020-10-22 14:30 UTC, mavam commented
I tested the feature with a custom URL concept that pulls data from Zeek and Suricata logs. Nice work! Just cosmetic stuff to be fixed.

2020-10-22 14:42 UTC, tobim commented on libvast/src/system/node.cpp
> +// factory.
In retrospect, the `invocation` based interface to the node turned out as less elegant that we'd hoped. I would like to replace it with something more type-safe at some point, but that will require one or two design sessions first.

2020-10-22 14:47 UTC, mavam approved these changes

2020-10-22 15:37 UTC, merged