Pin Apache Arrow version
tenzir/vast pull request #1104
Opened 2020-10-20 12:20 UTC by lava

2020-10-20 13:44 UTC, mavam commented
```
vast: error while loading shared libraries: libarrow.so.100: cannot open shared object file: No such file or directory
2244
```

2020-10-20 13:48 UTC, tobim requested changes
You need to update `github/workflows/jupyter.yaml` and `Dockerfile_prebuilt` too.

2020-10-20 15:01 UTC, mavam commented
@tenzir/backend IIRC we discussed adding a document on what to do when touching dependencies, because it's impossible that everyone remembers all the different places in the repo.

2020-10-20 16:13 UTC, tobim requested changes

2020-10-20 16:13 UTC, tobim commented on Dockerfile_prebuilt
> +  sudo apt-get -qqy install libarrow-dev=1.0.1-1
No sudo needed.

2020-10-20 21:15 UTC, tobim commented
`vast: error while loading shared libraries: libarrow.so.17: cannot open shared object file: No such file or directory`
in the jupyter tests.

2020-10-21 07:53 UTC, tobim commented
The runs of the jupyter workflow used vast-2020.06.25-26-gda6d112d, which is quite old. Is it set up like that intentionally? (@0ortmann)

2020-10-21 09:07 UTC, tobim approved these changes

2020-10-21 09:15 UTC, merged