Dont verify segment flatbuffers on startup
tenzir/vast pull request #1144
Opened 2020-11-05 09:47 UTC by lava

###  :notebook_with_decorative_cover: Description

###  :memo: Checklist

- [ ] All user-facing changes have changelog entries.
- [ ] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [ ] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

2020-11-05 09:56 UTC, mavam approved these changes
Looks good.

Please add some documentation to the utility and then feel free to merge.

2020-11-05 09:56 UTC, mavam commented on libvast/vast/fbs/utils.hpp
> +template <class Flatbuffer, size_t Extent = dynamic_extent>
Mind adding short documentation to this utility?

2020-11-05 10:04 UTC, lava commented
> EDIT: sorry, I overlooked that this is a draft PR. Ignore the merge part for now.

Maybe putting `wip: ` in the PR title has its uses after all ;p

2020-11-09 09:31 UTC, mavam approved these changes
LGTM. I didn't tested it again since you already reported the obvious performance numbers.

Optional: you could now call `as_unverified_flatbuffer` in the implementation of `as_flatbuffer`.

2020-11-09 09:51 UTC, dominiklohmann commented
Not quite sure what value `as_unverified_flatbuffer<RootType>(as_bytes(chunk))` provides over `fbs::GetRootType(chunk.data())`.

2020-11-09 09:53 UTC, dominiklohmann requested changes

2020-11-09 09:53 UTC, dominiklohmann commented on libvast/vast/fbs/utils.hpp
> +#include <dirent.h>
What's up with the new includes? I don't think `fbs/utils.hpp` should include the accountant, or `type.hpp`, or `dirent.h`, whatever that is.

2020-11-09 10:32 UTC, lava commented
> Not quite sure what value as_unverified_flatbuffer<fbs::RootType>(as_bytes(chunk)) provides over fbs::GetRootType(chunk.data()).

Yeah, good point.

2020-11-09 10:56 UTC, dominiklohmann requested changes

2020-11-09 10:56 UTC, dominiklohmann commented on libvast/vast/fbs/utils.hpp
> +/// @relates as_unverified_flatbuffer
```suggestion
```

2020-11-09 10:56 UTC, dominiklohmann commented on libvast/vast/fbs/utils.hpp
> +#include <algorithm>
```suggestion
```

2020-11-09 10:56 UTC, dominiklohmann commented on libvast/vast/fbs/utils.hpp
> +#include "vast/type.hpp"
```suggestion
```

2020-11-09 10:56 UTC, dominiklohmann commented on libvast/vast/fbs/utils.hpp
> +#include "vast/factory.hpp"
```suggestion
```

2020-11-09 10:56 UTC, dominiklohmann commented on libvast/src/segment_store.cpp
> +  // (see also dcso/ch1935)
```suggestion
  // (see also tdhtf/ch1935)
```

2020-11-09 12:19 UTC, dominiklohmann approved these changes
LGTM!

2020-11-09 13:05 UTC, merged