Enhance dump command to show models
tenzir/vast pull request #1233
Opened 2020-12-15 15:32 UTC by mavam

###  :notebook_with_decorative_cover: Description

This PR enhances the `dump` command to show models in addition to concepts.

###  :memo: Checklist

- [ ] All user-facing changes have changelog entries.
- [ ] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

File-by-file.

2020-12-15 16:03 UTC, dominiklohmann requested changes

2020-12-15 16:03 UTC, dominiklohmann commented on libvast/src/system/application.cpp
> +                       opts("?vast.dump.concepts"));
```suggestion
  dump->add_subcommand("models", "print all registered model definitions",
                       documentation::vast_dump_models,
                       opts("?vast.dump.models"));
```

And then the command docs are also missing.

2020-12-15 21:39 UTC, mavam commented
As the guardian of the integration test suite, @tobim may want to have a look at https://github.com/tenzir/vast/pull/1233/commits/89152f1485f063714f9cf3089e3b2d09498fdf4e and https://github.com/tenzir/vast/pull/1233/commits/9ecbfc889402ce0b9bd2af31d3e86cfa38ae081e.

2020-12-15 21:41 UTC, dominiklohmann approved these changes
Code-wise this is fine.

Can you change the documentation of `vast dump` itself so it reflects that it dumps both models and concepts?

Please wait for @tobim to review the integration test suite changes. I did not look at them.

2020-12-16 08:47 UTC, mavam commented
I'm handing this PR over to @tobim, who is going to investigate the non-determinism during concept dumping.

2020-12-16 15:14 UTC, mavam commented
Taking the PR back after internal sync.

2020-12-16 16:41 UTC, tobim requested changes
Just a suggestions to simplify the python code.

2020-12-16 16:41 UTC, tobim commented on integration/integration.py
> +    return bool(re.match(r"exp(ort|lore)|get|pivot", positionals[0]))
```suggestion
    return positionals[0] in {"export", "explore", "get", "pivot"}
```

2020-12-16 16:41 UTC, tobim commented on integration/integration.py
> +import re
```suggestion
```

2020-12-16 19:06 UTC, mavam commented
> You only take a const std::regex& here, so you should get away with forward-declaring it.

Is there a header for this, like we have for `<iosfwd>`?

> `<regex>` is one of the most expensive headers to include, and I'm not sure why we need it here. 

It makes for a convenient way to control the size of the return value.

>The default value is also crazy expensive. std::regex should never be created on the fly.

We're doing I/O here. And it's happening pretty much once at startup. The performance concerns don't appear to be in relation to the functionality.

2020-12-16 20:31 UTC, dominiklohmann approved these changes
This works fine.

Not printing empty descriptions / nested concepts / fields is a strict follow up and should not block the imminent release.

The `<regex>` stuff I'll clean up myself after the release, I created a story for that.

2020-12-16 20:32 UTC, merged