Dont create parallel meta index inside the index
tenzir/vast pull request #1292
Opened 2021-01-19 17:11 UTC by lava

###  :notebook_with_decorative_cover: Description

See commit messages.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Commit by commit

2021-01-19 17:22 UTC, tobim requested changes
Just a quick first pass, more to come later.

2021-01-19 17:22 UTC, tobim commented on libvast/vast/system/index_actor.hpp
>    // Replaces the SYNOPSIS of the PARTITION witht he given partition id.
```suggestion
  // Replaces the SYNOPSIS of the PARTITION with the given partition id.
```

2021-01-19 17:22 UTC, tobim commented on libvast/vast/system/index_actor.hpp
> +  caf::reacts_to<expression>, caf::reacts_to<expression, size_t>, // private
```suggestion
  caf::reacts_to<expression>, 
  // private
  caf::reacts_to<expression, size_t>,
```

2021-01-19 17:22 UTC, tobim commented on libvast/vast/meta_index.hpp
>    void merge(const uuid& partition, partition_synopsis&&);
This function should be called `add`.

2021-01-19 17:22 UTC, tobim commented on libvast/src/system/index.cpp
> +        VAST_DEBUG(self, "skips partition synopsis that is still in use");
This is not supposed to happen, so it should still be a warning.

2021-01-20 07:36 UTC, dominiklohmann reviewed
Just looked at this out of curiosity. Note that we should not use platform-dependent types like `size_t` in actor interfaces. Instead, use `uint64_t` or, which would be even better, use a distinct type that wraps an unsigned integer instead.

2021-01-20 07:36 UTC, dominiklohmann commented on libvast/src/system/index.cpp
> +#include <caf/typed_response_promise.hpp>
This can be removed.

2021-01-20 15:03 UTC, lava commented
Closing this in favor of the superior design in https://github.com/tenzir/vast/pull/1296

2021-01-20 15:03 UTC, closed without merging