Fix potential race condition between evaluator and partition
tenzir/vast pull request #1295
Opened 2021-01-20 15:01 UTC by lava

###  :notebook_with_decorative_cover: Description

###  :memo: Checklist

- [ ] All user-facing changes have changelog entries.
- [ ] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [ ] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

2021-01-21 08:15 UTC, tobim approved these changes
From looking at the changes, this seems to be correct and I do believe that the issue is real. I think one potential symptom is that a `query_supervisor` would miss a response from the cleaned-up partition and stay in limbo eternally, which in turn would block the corresponding exporter from iterating through the remaining candidate partitions.

2021-01-21 08:17 UTC, tobim requested changes
This is missing a changlog entry.

2021-01-22 11:48 UTC, dominiklohmann commented on CHANGELOG.md
> +  [#1295](https://github.com/tenzir/vast/pull/1295)
```suggestion
- 🐞 A potential race condition that could lead to a hanging export if
  a partition was persisted just as it was scanned no longer exists.
  [#1295](https://github.com/tenzir/vast/pull/1295)
```

2021-01-25 09:06 UTC, dominiklohmann commented
@lava can you rebase onto master?

2021-01-25 09:10 UTC, lava commented
@dominiklohmann Sorry, didn't notice until after I pushed. Done.

2021-01-25 09:10 UTC, dominiklohmann approved these changes
No functional changes happened since I last reviewed this. CI should catch rebase mistakes.

2021-01-25 09:59 UTC, lava commented
Ignoring the mac CI fault since it is https://app.clubhouse.io/tenzir/story/20882/race-condition-in-node-queries-unit-test again.

2021-01-25 10:00 UTC, merged