Use expected for chunk::mmap
tenzir/vast pull request #1509
Opened 2021-03-29 14:26 UTC by JoeLoser

###  :notebook_with_decorative_cover: Description

###  :memo: Checklist

- [ ] All user-facing changes have changelog entries.
- [ ] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [ ] The PR description contains instructions for the reviewer, if necessary.

Problem:
- There are multiple ways that `chunk::mmap` can not succeed. In some
  cases, it logs and returns a `nullptr`, and in other cases, just returns
  a `nullptr`. In the former case, this can lead to duplicate logging
  since the callers of `mmap` already log on failure. However, the
  callers lack sufficient information as to exactly which of the calls
  inside `mmap` made it fail.

Solution:
- Change the return type of `chunk::map` to leverage `caf::expected` so
  we can carry the error message back to the callers so it is known
  exactly what failed when trying to perform the mmap operation.

### :dart: Review Instructions

See top-level commit only as this is rebased off of https://github.com/tenzir/vast/pull/1504

2021-03-29 14:56 UTC, mavam commented
You can rebase this PR now, @JoeLoser.

2021-03-29 18:15 UTC, JoeLoser commented
> You can rebase this PR now, @JoeLoser.

Rebased 👍

2021-03-30 07:26 UTC, dominiklohmann requested changes
Just some very minor requests, other than that this looks really good. I double-checked that you caught all usages of `chunk::mmap`.

2021-03-30 07:26 UTC, dominiklohmann commented on libvast/src/chunk.cpp
> +      return caf::make_error(ec::filesystem_error,
Nit: You can remove the surrounding braces per our style guide.

2021-03-30 07:26 UTC, dominiklohmann commented on libvast/src/segment_store.cpp
> +                                       caf::to_string(chk.error().context())));
It suffices to forward the error here.

```suggestion
    return std::move(chk.error());
```

2021-03-30 07:26 UTC, dominiklohmann commented on libvast/src/segment_store.cpp
> +                                       caf::to_string(chk.error().context())));
Same as above: It suffices to forward the error here.

```suggestion
    return std::move(chk.error());
```

2021-03-30 07:26 UTC, dominiklohmann commented on libvast/src/system/index.cpp
> +                  caf::to_string(chunk.error().context())));
```suggestion
    return std::move(chunk.error());
```

2021-03-30 07:26 UTC, dominiklohmann commented on libvast/vast/chunk.hpp
>    /// @returns A chunk pointer or `nullptr` on failure.
```suggestion
  /// @returns A chunk pointer or an error on failure. The returned chunk
  /// pointer is never `nullptr`.
```

2021-03-30 13:42 UTC, JoeLoser commented
> Just some very minor requests, other than that this looks really good. I double-checked that you caught all usages of `chunk::mmap`.

Thanks for the review. I believe I've addressed all of the feedback comments; please re-review.

2021-03-30 14:11 UTC, merged