Streamline image build in vast-cloud
tenzir/vast pull request #2536
Opened 2022-08-29 14:01 UTC by rdettai

The current mechanism to build docker images for the cloud environment is hard to extend for new plugins (e.g the misp integration. 

### :memo: Reviewer Checklist

Review this pull request by ensuring the following items:

- [ ] All user-facing changes have changelog entries
- [ ] User-facing changes are reflected on [vast.io](https://github.com/tenzir/vast/tree/master/web)

2022-08-30 11:12 UTC, KaanSK commented
Had issues with dockerized aws client and after discussing with @rdettai we solved the issue. Dockerized AWS client file permissions on credentials file should be set properly. Just adding this as comment on review process. No further action is required.

2022-08-30 12:32 UTC, KaanSK commented
Would it make sense to add instruction to use `./vast-cloud init` for terraform required dependencies (I guess they are called external modules/libraries)? While reviewing this, I needed to use it.

2022-08-30 16:38 UTC, rdettai commented
> Dockerized AWS client file permissions on credentials file should be set properly.

To be more precise, the credentials file should be readable by the user executing `./vast-cloud`

> Would it make sense to add instruction to use ./vast-cloud init for terraform required dependencies (I guess they are called external modules/libraries)? While reviewing this, I needed to use it.

Yes I think a "troubleshooting" section would be very helpful

2022-08-31 10:29 UTC, rdettai commented
https://github.com/tenzir/vast/actions/runs/2963130323

2022-08-31 10:30 UTC, rdettai commented
@KaanSK I think I addressed both your comments:
- destroy failing when core modules not applied
- added comment abount init command

2022-08-31 11:45 UTC, KaanSK requested changes

2022-08-31 11:47 UTC, KaanSK commented on cloud/aws/cli/core.py
> +def docker_compose(step):
The review comments were before the https://github.com/tenzir/vast/pull/2536#issuecomment-1232760392 . @rdettai fixed the issue. No further action is required.

2022-08-31 11:47 UTC, KaanSK commented on cloud/aws/terraform/core-2/terragrunt.hcl
>    path = find_in_parent_folders("terragrunt.${get_env("TF_STATE_BACKEND")}.hcl")
The review comments were before the https://github.com/tenzir/vast/pull/2536#issuecomment-1232760392 . @rdettai fixed the issue. No further action is required.

2022-09-01 08:05 UTC, KaanSK commented
> 

Nothing else from my side. LGTM.

2022-09-02 07:25 UTC, KaanSK approved these changes

2022-09-02 07:25 UTC, merged