WIP - Reporting frontend
tenzir/vast pull request #2691
Opened 2022-11-09 07:58 UTC by dit7ya

### :memo: Reviewer Checklist

Review this pull request by ensuring the following items:

- [ ] All user-facing changes have changelog entries
- [ ] User-facing changes are reflected on [vast.io](https://github.com/tenzir/vast/tree/master/web)

2022-12-21 10:09 UTC, tobim commented
I think it makes sense to write the documentation after this feature has evolved a bit. Right now it is very much experimental and should not be advertised, but in order to make progress it would still be nice to have the scaffold and basic functionality in `master`.

2022-12-21 10:15 UTC, dit7ya reviewed
Remove the unneeded LayerCake stuff with a commit.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/components/IconButton.svelte
> +<script lang="ts">
This is not showing anywhere, whereas it needs to be on blocks' Edit and Delete buttons.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/components/Menu.svelte
> +  function classNames(...classes: (string | false | null | undefined)[]) {
Change to arrow functions.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/components/Table.svelte
> +                    ⬇️
Change the emoji to an icon.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/components/TextField.svelte
> +<script lang="ts">
Remove this leftover.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/util/api.ts
> +    // const url = `${API_BASE}/export?expression=${encodeURIComponent('#type == "zeek.conn" && id.orig_h in 192.168.0.0/16')}`;
Remove comment.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/lib/util/misc.ts
> +type ConnMinimal = {
Remove me (chart related).

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/Editor.svelte
> +<script lang="ts">
Rename me to something better.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/Editor.svelte
> +<script lang="ts">
Report Editor.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/Editor.svelte
> +    let fileName = 'vast-report.json'; // TODO use the title of the report
FIXME.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/Editor.svelte
> +  $: console.log($report);
REMOVE.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/Importer.svelte
> +    // console.log('A file has been added', fileItem);
Cleanup.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/MarkdownBlock.svelte
> +    title: 'TODO make me editable',
Here.

2022-12-21 10:54 UTC, dit7ya commented on plugins/web/ui/src/routes/report/QueryBlock.svelte
> +<script lang="ts">
Remove ME.

2023-01-02 09:43 UTC, mavam requested changes
This is great start!

Here's what I noticed playing with it:

### Report name bug

When I try to set a report name, remove all characters, I cannot get the box back:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/53797/210214113-245afb25-a50f-4dcf-82cf-b2c089101004.png">

### Icon weirdness

Per the above screenshot, the icons look a bit weird to me, with grey borders and some degree of pixelation. IIRC we wanted initially a very minimalistic black-and-white style. Maybe apply that here too?

### Moving cells

I couldn't find a way to move sections around via click-and-drag. I would expect this sort of functionality next to the edit and delete icon.

### Cell titles

When writing reports, I don't care too much about the cell title. Consider this:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/53797/210214845-e98e5a9d-02e5-463b-879c-80e364ba7a97.png">

### Heavy-weight horizontal separators

Per the above screenshot, I find the separators between the cells too much in the way. Can we downtone them? We could also make them vertical, so that the content reads cleanly but hoving over a cell demarcates the scope with a vertical bar on the right side, next to the other cell controls.

2023-01-03 14:02 UTC, mavam submitted a review, later dismissed
I found a few more things.

### Export overlay bug

This says it all:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/53797/210370276-1bce294a-699e-46c1-8678-191f49ebc6fd.png">

### PDF export includes export menu

Should also be clear from this screenshot:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/53797/210370569-1eb3fc90-78d6-4ca6-a2f3-4c80e9cc14c2.png">

### Global mode switch

When I've opened a few text boxes and I click the report button, all of these expand. Then I have to click save again on all of them to go into viewing mode. Could we have a global toggle?

2023-01-09 09:58 UTC, lava approved these changes
The code looks good to me on a high level, I think my Svelte still isn't strong enough to really comment on the details :D

As already discussed, I agree that it makes sense to merge this now and create separate stories for any outstanding bugs noticed by @mavam in his review.

Since we still have the whole frontend marked as experimental I'm not too worried about adding half-finished features, for the future it would probably be nice to introduce some feature toggle so we can develop this on master with "frontend-reporting=off" set by default and then we could flip the default to "on" once everything is done.

2023-01-09 10:55 UTC, tobim approved these changes
The functionality is in the state that we agreed on. I took only a cursory look at the code and didn't see any obvious issues.

2023-01-09 16:29 UTC, mavam approved these changes
Looking at the last 4 commits (code only), I would say this is in good shape now to ship.

2023-01-09 16:41 UTC, merged