Port streambuf.hpp from CAF 0.17.6 to VAST
tenzir/vast pull request #2761
Opened 2022-12-02 14:09 UTC by patszt

The streeambuf.hpp file gets removed in CAF 0.18.6
It is easier to just reuse it in VAST repo than trying to come up with custom solution for the problem it was solving.

2022-12-02 15:59 UTC, tobim requested changes
I think you should port the tests as well.

2022-12-03 20:41 UTC, mavam commented on libvast/include/vast/detail/streambuf.hpp
> +                         std::char_traits<typename Container::value_type>> {
Time flies. I remember that I contributed these very implementations to CAF years ago. Funny to see them now come "home" again.

2022-12-05 09:36 UTC, patszt commented on libvast/include/vast/detail/streambuf.hpp
> +                         std::char_traits<typename Container::value_type>> {
> I think you should port the tests as well.

done

2022-12-06 09:30 UTC, tobim approved these changes

2022-12-06 17:11 UTC, merged